aliases:  {
  name:  "aosp_current"
  target:  "ap2a"
}
description:  "Published open-source flags and declarations"
default_containers:  "product"
default_containers:  "system"
default_containers:  "system_ext"
default_containers:  "vendor"
