name: "RELEASE_BOARD_API_LEVEL"
namespace: "android_UNKNOWN"
description: "The API level of current vendor API surface. It has YYYYMM format."
value: {
  string_value: ""
}
workflow: MANUAL
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
