name:  "RELEASE_NDK_ABI_MONITORED"
namespace:  "android_UNKNOWN"
description:  "Enables ABI monitoring of NDK libraries."
value:  {
  bool_value:  false
}
workflow:  LAUNCH
containers:  "product"
containers:  "system"
containers:  "system_ext"
containers:  "vendor"
