name: "RELEASE_READ_FROM_NEW_STORAGE_CC"
namespace: "android_UNKNOWN"
description: "Enable reading from new storage from C/C++ aconfig flag codegen."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "system"
