name: "RELEASE_UPROBESTATS_MODULE"
namespace: "android_UNKNOWN"
description: "If true, then uprobestats module is enabled as an apex"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
