name: "RELEASE_AVF_ENABLE_VIRT_CPUFREQ"
namespace: "android_UNKNOWN"
description: "Enables Virtual Cpufreq support in Microdroid VM."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
