name: "RELEASE_AVF_ENABLE_NETWORK"
namespace: "android_virtualization"
description: "Adds supports for network functionality in VMs."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "system"
