name: "RELEASE_PLATFORM_SDK_EXTENSION_VERSION"
namespace: "android_UNKNOWN"
description: "The sdk extension version of this release configuration."
value: {
  string_value: "7"
}
workflow: MANUAL
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
