name:  "RELEASE_CREATE_ACONFIG_STORAGE_FILE"
namespace:  "android_UNKNOWN"
description:  "Enable build system to create new aconfig storage files."
value:  {
  bool_value:  false
}
workflow:  LAUNCH
containers:  "product"
containers:  "system"
containers:  "system_ext"
containers:  "vendor"
