name: "RELEASE_AVF_ENABLE_MICROFUCHSIA"
namespace: "android_platform_virtualization"
description: "Allows microfuchsia to run on AVF."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "system"
