name:  "RELEASE_PLATFORM_VERSION_KNOWN_CODENAMES"
namespace:  "android_UNKNOWN"
description:  "A comma separated list of all known codenames. For REL (finalized) configurations, it has to only contain finalized codenames."
value:  {
  string_value:  "Base,Base11,Cupcake,Donut,Eclair,Eclair01,EclairMr1,Froyo,Gingerbread,GingerbreadMr1,Honeycomb,HoneycombMr1,HoneycombMr2,IceCreamSandwich,IceCreamSandwichMr1,JellyBean,JellyBeanMr1,JellyBeanMr2,Kitkat,KitkatWatch,Lollipop,LollipopMr1,M,N,NMr1,O,OMr1,P,Q,R,S,Sv2,Tiramisu,UpsideDownCake,VanillaIceCream"
}
workflow:  MANUAL
containers:  "product"
containers:  "system"
containers:  "system_ext"
containers:  "vendor"
