name: "RELEASE_ACONFIG_CHECK_API_LEVEL"
namespace: "core_experiments_team_internal"
description: "Control checking the SDK level for exported flags guarding finalized APIs."
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
