name: "RELEASE_CRASHRECOVERY_MODULE"
namespace: "modularization"
description: "If true, then crashrecovery module is enabled as an apex"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
