name: "RELEASE_AVF_ALLOW_PREINSTALLED_APPS"
namespace: "android_virtualization"
description: "Enables acces to the AVF APIs to pre-installed apps."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "system"
