name: "RELEASE_MOVE_PDFRENDERER_TO_MODULE"
namespace: "android_UNKNOWN"
description: "If true, then files are moved from platform to apex"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"
