name: "RELEASE_AVF_ENABLE_EARLY_VM"
namespace: "android_UNKNOWN"
description: "Adds supports for VMs in the early boot, before /data mount."
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "system"
