name: "RELEASE_ONDEVICE_INTELLIGENCE_MODULE"
namespace: "ondeviceintelligence"
description: "If true, then files are moved from platform to apex"
value: {
  bool_value: false
}
workflow: LAUNCH
containers: "product"
containers: "system"
containers: "system_ext"
containers: "vendor"